### ISSUE TITLE
“https://rustwiki.org/zh-CN/” Certificate invalid

### ISSUE THREAD

**Issue by globaldarcy** [rust-lang-cn/rustwiki.org#2]
“https://rustwiki.org/zh-CN/” Certificate invalid, Please fix it as soon as possible, thanks

**Comment by globaldarcy** [comment]
This website cannot be opened in Google Chrome

**Comment by globaldarcy** [comment]
Thank you for your repairs and contributions

**Comment by globaldarcy** [comment]
“https://rustwiki.org/zh-CN/” Certificate invalid, Please fix it as soon as possible, thanks

**Comment by aaranxu** [comment]
谢谢提醒~
