### ISSUE TITLE
《Rust 程序设计语言》文档中的控制流没有数据

### ISSUE THREAD

**Issue by Engine-AI** [rust-lang-cn/rustwiki.org#24]
https://rustwiki.org/zh-CN/book/ch03-05-control-flow.html#%E6%8E%A7%E5%88%B6%E6%B5%81 没有数据 
https://rustwiki.org/en/book/ch03-05-control-flow.html 英文版有数据

**Comment by Engine-AI** [comment]
@aaranxu  hi！

**Comment by aaranxu** [comment]
已修复，感谢！
